# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mascota', '0004_auto_20180608_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('identificacion', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('razon', models.TextField()),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('ocupacion', models.TextField()),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mascota.Mascota')),
            ],
        ),
    ]
