# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.NullBooleanField(),
        ),
    ]
