# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-11 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0002_solicitudadopcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
