# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('raza', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='fotos')),
                ('video', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='Mascota.Vacuna'),
        ),
    ]
