# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0003_auto_20180608_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
