# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0004_auto_20180608_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
